### ISSUE TITLE
Baxter simulation in Kinetic and gazebo 10

### ISSUE THREAD

**Issue by faseehahmad** [RethinkRobotics/baxter_simulator#124]
Has anyone tried using baxter simulation in gazebo 10 and ros kinetic. I ran the following command
roslaunch baxter_gazebo baxter_world.launch

I got the following error

Segmentation fault (core dumped)
Segmentation fault (core dumped)
[gazebo-2] process has died [pid 17358, exit code 139, cmd /opt/ros/kinetic/lib/gazebo_ros/gzserver -e ode /home/faseeh/ros_ws/src/baxter_simulator/baxter_gazebo/worlds/baxter.world __name:=gazebo __log:=/home/faseeh/.ros/log/2428b7a4-4eab-11e8-8ffc-9cb6d067fc1f/gazebo-2.log].
log file: /home/faseeh/.ros/log/2428b7a4-4eab-11e8-8ffc-9cb6d067fc1f/gazebo-2*.log
[gazebo_gui-3] process has died [pid 17363, exit code 139, cmd /opt/ros/kinetic/lib/gazebo_ros/gzclient __name:=gazebo_gui __log:=/home/faseeh/.ros/log/2428b7a4-4eab-11e8-8ffc-9cb6d067fc1f/gazebo_gui-3.log].
log file: /home/faseeh/.ros/log/2428b7a4-4eab-11e8-8ffc-9cb6d067fc1f/gazebo_gui-3*.log

Any solution?

**Comment by zhaobinglei** [comment]
Did you solve this problem? I also met this problem!

**Comment by faseehahmad** [comment]
Nope. I just used ROS kinetic with gazebo 7.x. ROS kinetic supports gazebo 7.x.  Gazebo support for ROS:
http://gazebosim.org/tutorials?tut=ros_wrapper_versions
For later versions of gazebo, use ROS Melodic but Rethink does not have support for ROS versions after kinetic. So, I did not try them.

**Comment by rojas70** [comment]
Greetings, 

Using Ubuntu 16.04 with ROS Kinetic and Gazebo 7. 

Not sure if recently there was an upgrade to ros_control or similar. My baxter simulator used to run fine. 

Currently, these are the series of problems I have run into:

1. run `rolsaunch baxter_gazebo baxter_world.launch'
--> loading of gazebo hangs with a black window
--> Kill with ctrl+c and try again

2. Second time around, I get the following error messages:

[ERROR] [1556418086.690404985, 0.361000000]: GazeboRosControlPlugin missing <legacyModeNS> while using DefaultRobotHWSim, defaults to true.
This setting assumes you have an old package with an old implementation of DefaultRobotHWSim, where the robotNamespace is disregarded and absolute paths are used instead.
If you do not want to fix this issue in an old package just set <legacyModeNS> to true.



As well as:

````
[ INFO] [1556419610.453306040, 0.357000000]: Loaded gazebo_ros_control.
[ INFO] [1556419610.453750678, 0.357000000]: Loading Baxter specific simulation components
[ERROR] [1556419610.530289130, 0.415000000]: Cannot initialize this controller because it failed to be constructed
Traceback (most recent call last):
  File "/media/vmrguser/sdd/ros/kinetic/ros_ws/src/gym/pkg/ros_control/controller_manager/scripts/controller_manager", line 63, in <module>
    controller_manager_interface.load_controller(c)
  File "/media/vmrguser/sdd/ros/kinetic/ros_ws/src/gym/pkg/ros_control/controller_manager/src/controller_manager/controller_manager_interface.py", line 63, in load_controller
    resp = s.call(LoadControllerRequest(name))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 525, in call
    raise ServiceException("transport error completing service call: %s"%(str(e)))
rospy.service.ServiceException: transport error completing service call: unable to receive data from sender, check sender's logs for details
Traceback (most recent call last):
  File "/media/vmrguser/sdd/ros/kinetic/ros_ws/src/gym/pkg/ros_control/controller_manager/scripts/controller_manager", line 51, in <module>
    controller_manager_interface.load_controller(c)
  File "/media/vmrguser/sdd/ros/kinetic/ros_ws/src/gym/pkg/ros_control/controller_manager/src/controller_manager/controller_manager_interface.py", line 63, in load_controller
    resp = s.call(LoadControllerRequest(name))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 505, in call
Segmentation fault (core dumped)
    raise ServiceException("unable to connect to service: %s"%e)
rospy.service.ServiceException: unable to connect to service: [Errno 104] Connection reset by peer
[gazebo-2] process has died [pid 420, exit code 139, cmd /opt/ros/kinetic/lib/gazebo_ros/gzserver -e ode /media/vmrguser/sdd/ros/kinetic/ros_ws/src/robots/baxter/baxter_simulator/baxter_gazebo/worlds/baxter.world __name:=gazebo __log:=/media/vmrguser/sdd/ros/kinetic/log/d997ff12-695f-11e9-aeed-f0d5bf4fedef/gazebo-2.log].
log file: /media/vmrguser/sdd/ros/kinetic/log/d997ff12-695f-11e9-aeed-f0d5bf4fedef/gazebo-2*.log
[robot/controller_spawner-9] process has died [pid 455, exit code 1, cmd /media/vmrguser/sdd/ros/kinetic/ros_ws/src/gym/pkg/ros_control/controller_manager/scripts/controller_manager spawn joint_state_controller __name:=controller_spawner __log:=/media/vmrguser/sdd/ros/kinetic/log/d997ff12-695f-11e9-aeed-f0d5bf4fedef/robot-controller_spawner-9.log].
log file: /media/vmrguser/sdd/ros/kinetic/log/d997ff12-695f-11e9-aeed-f0d5bf4fedef/robot-controller_spawner-9*.log
[robot/right_gripper_controller_spawner_stopped-12] process has died [pid 482, exit code 1, cmd /media/vmrguser/sdd/ros/kinetic/ros_ws/src/gym/pkg/ros_control/controller_manager/scripts/controller_manager load right_gripper_controller __name:=right_gripper_controller_spawner_stopped __log:=/media/vmrguser/sdd/ros/kinetic/log/d997ff12-695f-11e9-aeed-f0d5bf4fedef/robot-right_gripper_controller_spawner_stopped-12.log].
log file: /media/vmrguser/sdd/ros/kinetic/log/d997ff12-695f-11e9-aeed-f0d5bf4fedef/robot-right_gripper_controller_spawner_stopped-12*.log



If I set legacyNS to false as per:
https://answers.ros.org/question/292444/gazebo_ros_control-plugin-gazeboroscontrolplugin-missing-legacymodens-defaultrobothwsim/

I also get the following errors:
````
[ERROR] [1556419176.689849741, 0.358000000]: Cannot initialize this controller because it failed to be constructed
Traceback (most recent call last):
  File "/media/vmrguser/sdd/ros/kinetic/ros_ws/src/gym/pkg/ros_control/controller_manager/scripts/controller_manager", line 63, in <module>
    controller_manager_interface.load_controller(c)
  File "/media/vmrguser/sdd/ros/kinetic/ros_ws/src/gym/pkg/ros_control/controller_manager/src/controller_manager/controller_manager_interface.py", line 63, in load_controller
    resp = s.call(LoadControllerRequest(name))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 525, in call
    raise ServiceException("transport error completing service call: %s"%(str(e)))
rospy.service.ServiceException: transport error completing service call: unable to receive data from sender, check sender's logs for details
Traceback (most recent call last):
Traceback (most recent call last):
Segmentation fault (core dumped)
  File "/media/vmrguser/sdd/ros/kinetic/ros_ws/src/gym/pkg/ros_control/controller_manager/scripts/controller_manager", line 51, in <module>
    controller_manager_interface.load_controller(c)
  File "/media/vmrguser/sdd/ros/kinetic/ros_ws/src/gym/pkg/ros_control/controller_manager/src/controller_manager/controller_manager_interface.py", line 63, in load_controller
    resp = s.call(LoadControllerRequest(name))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 505, in call
    raise ServiceException("unable to connect to service: %s"%e)
rospy.service.ServiceException: unable to connect to service: [Errno 104] Connection reset by peer
  File "/media/vmrguser/sdd/ros/kinetic/ros_ws/src/gym/pkg/ros_control/controller_manager/scripts/controller_manager", line 51, in <module>
    controller_manager_interface.load_controller(c)
  File "/media/vmrguser/sdd/ros/kinetic/ros_ws/src/gym/pkg/ros_control/controller_manager/src/controller_manager/controller_manager_interface.py", line 63, in load_controller
    resp = s.call(LoadControllerRequest(name))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 505, in call
    raise ServiceException("unable to connect to service: %s"%e)
rospy.service.ServiceException: unable to connect to service: [Errno 104] Connection reset by peer
[gazebo-2] process has died [pid 27540, exit code 139, cmd /opt/ros/kinetic/lib/gazebo_ros/gzserver -e ode /media/vmrguser/sdd/ros/kinetic/ros_ws/src/robots/baxter/baxter_simulator/baxter_gazebo/worlds/baxter.world __name:=gazebo __log:=/media/vmrguser/sdd/ros/kinetic/log/d71c5856-695e-11e9-aeed-f0d5bf4fedef/gazebo-2.log].
log file: /media/vmrguser/sdd/ros/kinetic/log/d71c5856-695e-11e9-aeed-f0d5bf4fedef/gazebo-2*.log
[robot/controller_spawner-9] process has died [pid 27574, exit code 1, cmd /media/vmrguser/sdd/ros/kinetic/ros_ws/src/gym/pkg/ros_control/controller_manager/scripts/controller_manager spawn joint_state_controller __name:=controller_spawner __log:=/media/vmrguser/sdd/ros/kinetic/log/d71c5856-695e-11e9-aeed-f0d5bf4fedef/robot-controller_spawner-9.log].
log file: /media/vmrguser/sdd/ros/kinetic/log/d71c5856-695e-11e9-aeed-f0d5bf4fedef/robot-controller_spawner-9*.log
[robot/controller_spawner_stopped-10] process has died [pid 27587, exit code 1, cmd /media/vmrguser/sdd/ros/kinetic/ros_ws/src/gym/pkg/ros_control/controller_manager/scripts/controller_manager load left_joint_position_controller right_joint_position_controller head_position_controller left_joint_velocity_controller right_joint_velocity_controller left_joint_effort_controller right_joint_effort_controller __name:=controller_spawner_stopped __log:=/media/vmrguser/sdd/ros/kinetic/log/d71c5856-695e-11e9-aeed-f0d5bf4fedef/robot-controller_spawner_stopped-10.log].
log file: /media/vmrguser/sdd/ros/kinetic/log/d71c5856-695e-11e9-aeed-f0d5bf4fedef/robot-controller_spawner_stopped-10*.log
[robot/right_gripper_controller_spawner_stopped-12] process has died [pid 27597, exit code 1, cmd /media/vmrguser/sdd/ros/kinetic/ros_ws/src/gym/pkg/ros_control/controller_manager/scripts/controller_manager load right_gripper_controller __name:=right_gripper_controller_spawner_stopped __log:=/media/vmrguser/sdd/ros/kinetic/log/d71c5856-695e-11e9-aeed-f0d5bf4fedef/robot-right_gripper_controller_spawner_stopped-12.log].
log file: /media/vmrguser/sdd/ros/kinetic/log/d71c5856-695e-11e9-aeed-f0d5bf4fedef/robot-right_gripper_controller_spawner_stopped-12*.log




If I set it to true I get:

gzserver: /usr/include/boost/smart_ptr/shared_ptr.hpp:648: typename boost::detail::sp_member_access<T>::type boost::shared_ptr<T>::operator->() const [with T = const urdf::Joint; typename boost::detail::sp_member_access<T>::type = const urdf::Joint*]: Assertion `px != 0' failed.
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/controller_manager/controller_manager", line 46, in <module>
    controller_manager_interface.load_controller(c)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/controller_manager/controller_manager_interface.py", line 58, in load_controller
    resp = s.call(LoadControllerRequest(name))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 525, in call
    raise ServiceException("transport error completing service call: %s"%(str(e)))
rospy.service.ServiceException: transport error completing service call: unable to receive data from sender, check sender's logs for details
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/controller_manager/controller_manager", line 46, in <module>
    controller_manager_interface.load_controller(c)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/controller_manager/controller_manager_interface.py", line 58, in load_controller
    resp = s.call(LoadControllerRequest(name))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 505, in call
    raise ServiceException("unable to connect to service: %s"%e)
rospy.service.ServiceException: unable to connect to service: [Errno 104] Connection reset by peer
Aborted (core dumped)
[gazebo-2] process has died [pid 19604, exit code 134, cmd /opt/ros/kinetic/lib/gazebo_ros/gzserver -e ode /media/vmrguser/sdd/ros/kinetic/ros_ws/src/robots/baxter/baxter_simulator/baxter_gazebo/worlds/baxter.world __name:=gazebo __log:=/media/vmrguser/sdd/ros/kinetic/log/46b68aca-6968-11e9-aeed-f0d5bf4fedef/gazebo-2.log].
log file: /media/vmrguser/sdd/ros/kinetic/log/46b68aca-6968-11e9-aeed-f0d5bf4fedef/gazebo-2*.log
[robot/left_gripper_controller_spawner_stopped-11] process has died [pid 19638, exit code 1, cmd /opt/ros/kinetic/lib/controller_manager/controller_manager load left_gripper_controller __name:=left_gripper_controller_spawner_stopped __log:=/media/vmrguser/sdd/ros/kinetic/log/46b68aca-6968-11e9-aeed-f0d5bf4fedef/robot-left_gripper_controller_spawner_stopped-11.log].
log file: /media/vmrguser/sdd/ros/kinetic/log/46b68aca-6968-11e9-aeed-f0d5bf4fedef/robot-left_gripper_controller_spawner_stopped-11*.log
[robot/right_gripper_controller_spawner_stopped-12] process has died [pid 19644, exit code 1, cmd /opt/ros/kinetic/lib/controller_manager/controller_manager load right_gripper_controller __name:=right_gripper_controller_spawner_stopped __log:=/media/vmrguser/sdd/ros/kinetic/log/46b68aca-6968-11e9-aeed-f0d5bf4fedef/robot-right_gripper_controller_spawner_stopped-12.log].
log file: /media/vmrguser/sdd/ros/kinetic/log/46b68aca-6968-11e9-aeed-f0d5bf4fedef/robot-right_gripper_controller_spawner_stopped-12*.log
[ INFO] [1556423228.909109681, 0.362000000]: Topic '/robot/xdisplay' waiting for subscriber...
[INFO] [1556423229.217608, 0.362000]: Calling service /gazebo/set_model_configuration
Service call failed: unable to connect to service: [Errno 111] Connection refused



I would appreciate any feedback.
